#PANDAS KÜTÜPHANESİNE GİRİŞ


## PANDAS SERİSİ OLUŞTURMA

In [1]:
import pandas as pd

In [2]:
pd.Series([1,4,2,7,3,5])

0    1
1    4
2    2
3    7
4    3
5    5
dtype: int64

In [3]:
seri = pd.Series([1,4,2,7,3,5])

In [4]:
type(seri)

pandas.core.series.Series

In [5]:
seri.axes

[RangeIndex(start=0, stop=6, step=1)]

In [6]:
seri.dtype

dtype('int64')

In [7]:
seri.size

6

In [8]:
seri.ndim

1

In [9]:
seri.values

array([1, 4, 2, 7, 3, 5], dtype=int64)

In [10]:
seri.head(3)

0    1
1    4
2    2
dtype: int64

In [11]:
seri.head()

0    1
1    4
2    2
3    7
4    3
dtype: int64

In [12]:
seri.tail()

1    4
2    2
3    7
4    3
5    5
dtype: int64

In [13]:
# index isimlendirmesi

In [14]:
pd.Series([99,22,33,44,55])

0    99
1    22
2    33
3    44
4    55
dtype: int64

In [15]:
pd.Series([99,22,33,44,55],index = [1,3,5,4,0])

1    99
3    22
5    33
4    44
0    55
dtype: int64

In [16]:
seri2 = pd.Series([99,22,33,44,55],index = ["a","b","c","d","e"])

In [17]:
seri2[0]

99

In [18]:
seri2["a"]

99

In [19]:
seri2["a":"c"]

a    99
b    22
c    33
dtype: int64

In [20]:
# sözlük üzerinden liste oluşturmak

In [21]:
sozluk = pd.Series({"reg":10,"log":11,"cart":12})

In [22]:
sozluk

reg     10
log     11
cart    12
dtype: int64

In [23]:
new_dict = {"a":1,"b":2,"c":3}

In [24]:
new_seri = pd.Series(new_dict)

In [25]:
new_seri

a    1
b    2
c    3
dtype: int64

In [26]:
# iki seriyi birleştirerek oluşturma

In [27]:
pd.concat([sozluk,new_seri])

reg     10
log     11
cart    12
a        1
b        2
c        3
dtype: int64

# ELEMAN İŞLEMLERİ

In [28]:
import numpy as np
a= np.array([1,2,3,4,5])
seri = pd.Series(a)
seri

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [29]:
seri[0]

1

In [30]:
seri[0:3]

0    1
1    2
2    3
dtype: int32

In [31]:
seri = pd.Series([100,122,133,145,153,167],
                index=["a","b","c","d","e","f"])

In [32]:
seri

a    100
b    122
c    133
d    145
e    153
f    167
dtype: int64

In [33]:
seri.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [34]:
seri.keys

<bound method Series.keys of a    100
b    122
c    133
d    145
e    153
f    167
dtype: int64>

In [35]:
seri.values

array([100, 122, 133, 145, 153, 167], dtype=int64)

In [36]:
seri.items

<bound method Series.iteritems of a    100
b    122
c    133
d    145
e    153
f    167
dtype: int64>

In [37]:
list(seri.items())

[('a', 100), ('b', 122), ('c', 133), ('d', 145), ('e', 153), ('f', 167)]

In [38]:
list(seri.values)

[100, 122, 133, 145, 153, 167]

In [39]:
"a" in seri

True

In [40]:
"w" in seri

False

In [41]:
# fancy ile elemana erişim

In [42]:
seri[["a","b"]]

a    100
b    122
dtype: int64

In [43]:
seri["a"] = 111

In [44]:
seri["a"]

111

In [45]:
seri["a":"f"]

a    111
b    122
c    133
d    145
e    153
f    167
dtype: int64

# Pandas DataFrame Oluşturma

In [46]:
import pandas as pd

In [47]:
liste = [1,2,3,4,5,6,7,8,9]

In [48]:
liste

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
pd.DataFrame(liste,columns=["değişken adı"])

değişken adı
0             1
1             2
2             3
3             4
4             5
5             6
6             7
7             8
8             9

In [50]:
import numpy as np

In [51]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
pd.DataFrame(m,columns=["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [53]:
df = pd.DataFrame(m,columns=["var1","var2","var3"])

In [54]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [55]:
df.head(1)

var1  var2  var3
0     1     2     3

In [56]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [57]:
df.columns = ("deg1","deg2","deg3")

In [58]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [59]:
type(df)

pandas.core.frame.DataFrame

In [60]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [61]:
df.shape

(3, 3)

In [62]:
df.ndim

2

In [63]:
df.size

9

In [64]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
type(df.values)

numpy.ndarray

In [66]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [67]:
df.tail()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [68]:
a = np.array([1,2,3,4])

In [69]:
pd.DataFrame(a,columns=["degerler"])

degerler
0         1
1         2
2         3
3         4

# Pandas DataFrame Eleman İşlemleri

In [70]:
import numpy as np

In [71]:
s1 = np.random.randint(10,size=5)
s2 = np.random.randint(10,size=5)
s3 = np.random.randint(10,size=5)

In [72]:
s1

array([6, 2, 7, 0, 0])

In [73]:
s2

array([2, 7, 2, 8, 4])

In [74]:
s3

array([0, 6, 4, 5, 6])

In [75]:
sozluk = {"var1":s1, "var2":s2, "var3":s3}

In [76]:
sozluk

{'var1': array([6, 2, 7, 0, 0]),
 'var2': array([2, 7, 2, 8, 4]),
 'var3': array([0, 6, 4, 5, 6])}

In [97]:
df = pd.DataFrame(sozluk)

In [80]:
df

var1  var2  var3
0     6     2     0
1     2     7     6
2     7     2     4
3     0     8     5
4     0     4     6

In [81]:
df[0:1]

var1  var2  var3
0     6     2     0

In [82]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [83]:
df.index = ["a","b","c","d","e"]

In [84]:
df

var1  var2  var3
a     6     2     0
b     2     7     6
c     7     2     4
d     0     8     5
e     0     4     6

In [85]:
df["c":"e"]

var1  var2  var3
c     7     2     4
d     0     8     5
e     0     4     6

In [86]:
# silme işlemleri

In [87]:
df.drop("a",axis=0)

var1  var2  var3
b     2     7     6
c     7     2     4
d     0     8     5
e     0     4     6

In [88]:
df

var1  var2  var3
a     6     2     0
b     2     7     6
c     7     2     4
d     0     8     5
e     0     4     6

In [89]:
df.drop("a",axis=0, inplace = True)

In [90]:
df

var1  var2  var3
b     2     7     6
c     7     2     4
d     0     8     5
e     0     4     6

In [91]:
# fancy ile silme işlemi

In [93]:
l =["c","e"]

In [94]:
df.drop(l,axis=0)

var1  var2  var3
b     2     7     6
d     0     8     5

In [99]:
df

var1  var2  var3
0     6     2     0
1     2     7     6
2     7     2     4
3     0     8     5
4     0     4     6

In [101]:
"var1" in df

True

In [104]:
k = ["var1","var2","var6"]

In [106]:
for i in k:
    print(i in df)
    

True
True
False


In [107]:
df

var1  var2  var3
0     6     2     0
1     2     7     6
2     7     2     4
3     0     8     5
4     0     4     6

In [108]:
df["var4"] = df["var1"] / df["var2"] 

In [109]:
df

var1  var2  var3      var4
0     6     2     0  3.000000
1     2     7     6  0.285714
2     7     2     4  3.500000
3     0     8     5  0.000000
4     0     4     6  0.000000

In [110]:
# değişken silmek

In [114]:
df.drop("var4", axis=1,inplace = True)

In [115]:
df

var1  var2  var3
0     6     2     0
1     2     7     6
2     7     2     4
3     0     8     5
4     0     4     6

In [116]:
l = ["var1","var2"]

In [117]:
df.drop(l, axis=1)

var3
0     0
1     6
2     4
3     5
4     6

# GÖZLEM VE DEĞİŞKEN SEÇİMİ (loc & iloc)

In [1]:
import numpy as np
import pandas as pd

In [2]:
m = np.random.randint(1,30,size=(10,3))
df = pd.DataFrame(m,columns = ["var1","var2","var3"])
df

var1  var2  var3
0    10    13     5
1     2     5     7
2     4    27    23
3    20    27    11
4     3    17    15
5    14    13    14
6     8     6    29
7    25    17     2
8    28    26    22
9    14    23     2

In [ ]:
# loc : tanımlandığı şekli ile seçim yapmak için kullanılır.

In [5]:
df.loc[0:3]

var1  var2  var3
0    10    13     5
1     2     5     7
2     4    27    23
3    20    27    11

In [6]:
# iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [7]:
df.iloc[0:3]

var1  var2  var3
0    10    13     5
1     2     5     7
2     4    27    23

In [8]:
df.iloc[:3,:2]

var1  var2
0    10    13
1     2     5
2     4    27

In [10]:
df.loc[0:3,"var3"]

0     5
1     7
2    23
3    11
Name: var3, dtype: int32

In [14]:
df.iloc[0:3,1:3]["var3"]

0     5
1     7
2    23
Name: var3, dtype: int32

# KOŞULLU ELEMAN İŞLEMLERİ

In [15]:
import numpy as np
import pandas as pd

In [16]:
m = np.random.randint(1,30,size=(10,3))
df = pd.DataFrame(m,columns = ["var1","var2","var3"])
df

var1  var2  var3
0     1     1    12
1    19    24     4
2    24    29     8
3    26    12    25
4     3    27    12
5    27    24    23
6    12    16     6
7    10    11     3
8     2    19    18
9    14    10    18

In [17]:
df["var1"]

0     1
1    19
2    24
3    26
4     3
5    27
6    12
7    10
8     2
9    14
Name: var1, dtype: int32

In [18]:
df["var1"][0:2]

0     1
1    19
Name: var1, dtype: int32

In [19]:
df[0:2]

var1  var2  var3
0     1     1    12
1    19    24     4

In [20]:
df[0:2]["var1"]

0     1
1    19
Name: var1, dtype: int32

In [22]:
df[0:2][["var1","var2"]]

var1  var2
0     1     1
1    19    24

In [23]:
df

var1  var2  var3
0     1     1    12
1    19    24     4
2    24    29     8
3    26    12    25
4     3    27    12
5    27    24    23
6    12    16     6
7    10    11     3
8     2    19    18
9    14    10    18

In [24]:
# example: var1'deki değişkenlerin 15 değerinden büyük olması durumu


In [25]:
df["var1"]

0     1
1    19
2    24
3    26
4     3
5    27
6    12
7    10
8     2
9    14
Name: var1, dtype: int32

In [27]:
df.var1 == df["var1"]

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: var1, dtype: bool

In [28]:
df[df.var1>15]

var1  var2  var3
1    19    24     4
2    24    29     8
3    26    12    25
5    27    24    23

In [29]:
df[df.var1>15]["var1"]

1    19
2    24
3    26
5    27
Name: var1, dtype: int32

In [30]:
df[df.var1>15].var1

1    19
2    24
3    26
5    27
Name: var1, dtype: int32

In [31]:
# ikili koşullu işlemler için 

In [33]:
df[(df.var1>15) & (df.var3<5)]

var1  var2  var3
1    19    24     4

In [34]:
df.loc[(df.var1>15),["var1","var2"]]

var1  var2
1    19    24
2    24    29
3    26    12
5    27    24

In [35]:
df[(df.var1>15)][["var1","var2"]]

var1  var2
1    19    24
2    24    29
3    26    12
5    27    24

# BİRLEŞTİRME (JOIN) İŞLEMLERİ

In [39]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m,columns=["var1","var2","var3"])
df1

var1  var2  var3
0    10    14    26
1    21    20     4
2    20    29    14
3    12    16     4
4    21     2    28

In [41]:
df2 = df1+10

In [42]:
df2

var1  var2  var3
0    20    24    36
1    31    30    14
2    30    39    24
3    22    26    14
4    31    12    38

In [47]:
pd.concat([df1,df2],ignore_index=True)

var1  var2  var3
0    10    14    26
1    21    20     4
2    20    29    14
3    12    16     4
4    21     2    28
5    20    24    36
6    31    30    14
7    30    39    24
8    22    26    14
9    31    12    38

In [45]:
?pd.concat

Signature:
pd.concat(
    ['objs', 'axis=0', "join='outer'", 'join_axes=None', 'ignore_index=False', 'keys=None', 'levels=None', 'names=None', 'verify_integrity=False', 'sort=None', 'copy=True'],
)
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series, DataFrame, or Panel objects
    If a dict is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised
axis : {0/'index', 1/'columns'}, default 0
    The axis to concatenate along
join : {'inner', 'outer'}, default 'outer'
    How to handle indexes on other axis(es)

In [52]:
print(df1.columns)
print(df2.columns)

Index(['var1', 'var2', 'var3'], dtype='object')
Index(['var1', 'var2', 'var3'], dtype='object')


In [53]:
df2.columns=["var1","var2","deg3"]

In [55]:
df2

var1  var2  deg3
0    20    24    36
1    31    30    14
2    30    39    24
3    22    26    14
4    31    12    38

In [56]:
df1

var1  var2  var3
0    10    14    26
1    21    20     4
2    20    29    14
3    12    16     4
4    21     2    28

In [60]:
pd.concat([df1,df2],ignore_index=True)

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


deg3  var1  var2  var3
0   NaN    10    14  26.0
1   NaN    21    20   4.0
2   NaN    20    29  14.0
3   NaN    12    16   4.0
4   NaN    21     2  28.0
5  36.0    20    24   NaN
6  14.0    31    30   NaN
7  24.0    30    39   NaN
8  14.0    22    26   NaN
9  38.0    31    12   NaN

In [61]:
pd.concat([df1,df2],join="inner") # kesişimlerine göre birleştirdi

var1  var2
0    10    14
1    21    20
2    20    29
3    12    16
4    21     2
0    20    24
1    31    30
2    30    39
3    22    26
4    31    12

In [63]:
pd.concat([df1,df2],join_axes= [df1.columns], ignore_index=True)

var1  var2  var3
0    10    14  26.0
1    21    20   4.0
2    20    29  14.0
3    12    16   4.0
4    21     2  28.0
5    20    24   NaN
6    31    30   NaN
7    30    39   NaN
8    22    26   NaN
9    31    12   NaN

# İLERİ BİRLEŞTİRME İŞLEMLERİ

In [64]:
import pandas as pd

In [65]:
# birebir birleştirme

In [67]:
df1 = pd.DataFrame({"calisanlar":["Ali","Ayse","Kemal","Deniz"],
                   "grup":["Muhasebe","Mühendislik","Mühendislik","İK"]})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Ayse  Mühendislik
2      Kemal  Mühendislik
3      Deniz           İK

In [68]:
df2 = pd.DataFrame({"calisanlar":["Ali","Ayse","Kemal","Deniz"],
                   "ilk_giris":[2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0        Ali       2010
1       Ayse       2009
2      Kemal       2014
3      Deniz       2019

In [69]:
pd.merge(df1,df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2010
1       Ayse  Mühendislik       2009
2      Kemal  Mühendislik       2014
3      Deniz           İK       2019

In [70]:
pd.merge(df1,df2, on = "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2010
1       Ayse  Mühendislik       2009
2      Kemal  Mühendislik       2014
3      Deniz           İK       2019

In [71]:
# çoktan teke birleştirme (many to one)

In [73]:
df3 = pd.merge(df1,df2)
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2010
1       Ayse  Mühendislik       2009
2      Kemal  Mühendislik       2014
3      Deniz           İK       2019

In [74]:
df4 = pd.DataFrame({"grup":["Muhasebe","Mühendislik","İK"],
                   "mudur":["Caner","Mustafa","Ayhan"]})
df4

grup    mudur
0     Muhasebe    Caner
1  Mühendislik  Mustafa
2           İK    Ayhan

In [75]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2010    Caner
1       Ayse  Mühendislik       2009  Mustafa
2      Kemal  Mühendislik       2014  Mustafa
3      Deniz           İK       2019    Ayhan

In [76]:
# many to many birleştirme

In [78]:
df5 = pd.DataFrame({"grup":["Muhasebe","Muhasebe","Mühendislik","Mühendislik","İK","İK"],
                   "yetenekler":["Matematik","Excel","Kodlama","Linux","Excel","Yonetim"]})

df5

grup yetenekler
0     Muhasebe  Matematik
1     Muhasebe      Excel
2  Mühendislik    Kodlama
3  Mühendislik      Linux
4           İK      Excel
5           İK    Yonetim

In [79]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Ayse  Mühendislik
2      Kemal  Mühendislik
3      Deniz           İK

In [80]:
pd.merge(df1,df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  Matematik
1        Ali     Muhasebe      Excel
2       Ayse  Mühendislik    Kodlama
3       Ayse  Mühendislik      Linux
4      Kemal  Mühendislik    Kodlama
5      Kemal  Mühendislik      Linux
6      Deniz           İK      Excel
7      Deniz           İK    Yonetim

# Aggregation & Grouping İşlemleri

In [81]:
 import seaborn as sns

In [82]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load a dataset from the online repository (requires internet).

Parameters
----------
name : str
    Name of the dataset (`name`.csv on
    https://github.com/mwaskom/seaborn-data).  You can obtain list of
    available datasets using :func:`get_dataset_names`
cache : boolean, optional
    If True, then cache data locally and use the cache on subsequent calls
data_home : string, optional
    The directory in which to cache data. By default, uses ~/seaborn-data/
kws : dict, optional
    Passed to pandas.read_csv
File:      c:\users\user\anaconda3\lib\site-packages\seaborn\utils.py
Type:      function


In [85]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [86]:
df.shape

(1035, 6)

In [87]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [88]:
df["mass"].mean()

2.6381605847953233

In [89]:
df["mass"].count()

513

In [90]:
df["year"].count()

1035

In [92]:
df["mass"].min()

0.0036

In [93]:
df["mass"].max()

25.0

In [94]:
df["mass"].sum()

1353.37638

In [95]:
df["mass"].std()

3.8186166509616046

In [96]:
df["mass"].var()

14.58183312700122

In [97]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [98]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [99]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# GRUPLAMA İŞLEMLERİ

In [102]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                  "veri":[90,51,34,13,77,21]},
                  columns=["gruplar","veri"])
df

gruplar  veri
0       A    90
1       B    51
2       C    34
3       A    13
4       B    77
5       C    21

In [103]:
df.groupby("gruplar")

In [104]:
df.groupby("gruplar").mean()

veri
gruplar      
A        51.5
B        64.0
C        27.5

In [105]:
df.groupby("gruplar").sum()

veri
gruplar      
A         103
B         128
C          55

In [107]:
df_planets = sns.load_dataset("planets")
df_planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [110]:
df_planets.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [112]:
df_planets.groupby("method")["orbital_period"].describe().T

method   Astrometry  Eclipse Timing Variations        Imaging  Microlensing  \
count      2.000000                   9.000000      12.000000      7.000000   
mean     631.180000                4751.644444  118247.737500   3153.571429   
std      544.217663                2499.130945  213978.177277   1113.166333   
min      246.360000                1916.250000    4639.150000   1825.000000   
25%      438.770000                2900.000000    8343.900000   2375.000000   
50%      631.180000                4343.500000   27500.000000   3300.000000   
75%      823.590000                5767.000000   94250.000000   3550.000000   
max     1016.000000               10220.000000  730000.000000   5100.000000   

method  Orbital Brightness Modulation  Pulsar Timing  \
count                        3.000000       5.000000   
mean                         0.709307    7343.021201   
std                          0.725493   16313.265573   
min                          0.240104       0.090706   
25%                          0.291496      25.262000   
50%                          0.342887      66.541900   
75%                          0.943908      98.211400   
max                          1.544929   36525.000000   

method  Pulsation Timing Variations  Radial Velocity     Transit  \
count                           1.0        553.00000  397.000000   
mean                         1170.0        823.35468   21.102073   
std                             NaN       1454.92621   46.185893   
min                          1170.0          0.73654    0.355000   
25%                          1170.0         38.02100    3.160630   
50%                          1170.0        360.20000    5.714932   
75%                          1170.0        982.00000   16.145700   
max                          1170.0      17337.50000  331.600590   

method  Transit Timing Variations  
count                    3.000000  
mean                    79.783500  
std                     71.599884  
min                     22.339500  
25%                     39.675250  
50%                     57.011000  
75%                    108.505500  
max                    160.000000

# İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)

In [118]:
import pandas as pd
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                  "DEG1":[10,20,30,12,23,55],
                  "DEG2":[111,132,565,232,56,23]},
                 columns=["gruplar","DEG1","DEG2"])
df

gruplar  DEG1  DEG2
0       A    10   111
1       B    20   132
2       C    30   565
3       A    12   232
4       B    23    56
5       C    55    23

In [119]:
# aggregate

In [121]:
df.groupby("gruplar").mean()

DEG1   DEG2
gruplar             
A        11.0  171.5
B        21.5   94.0
C        42.5  294.0

In [123]:
df.groupby("gruplar").aggregate([min,np.median,max])

DEG1            DEG2            
         min median max  min median  max
gruplar                                 
A         10   11.0  12  111  171.5  232
B         20   21.5  23   56   94.0  132
C         30   42.5  55   23  294.0  565

In [125]:
df.groupby("gruplar").aggregate({"DEG1":min,
                                 "DEG2":max
                                })

DEG1  DEG2
gruplar            
A          10   232
B          20   132
C          30   565

In [126]:
# filter

In [127]:
import pandas as pd
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                  "DEG1":[10,20,30,12,23,55],
                  "DEG2":[111,132,565,232,56,23]},
                 columns=["gruplar","DEG1","DEG2"])
df


gruplar  DEG1  DEG2
0       A    10   111
1       B    20   132
2       C    30   565
3       A    12   232
4       B    23    56
5       C    55    23

In [132]:
def filter_func(x):
    return x["DEG1"].std()>10

In [134]:
df.groupby("gruplar").std()

DEG1        DEG2
gruplar                       
A         1.414214   85.559921
B         2.121320   53.740115
C        17.677670  383.251875

In [133]:
df.groupby("gruplar").filter(filter_func)

gruplar  DEG1  DEG2
2       C    30   565
5       C    55    23

In [ ]:
# Transform

In [135]:
import pandas as pd
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                  "DEG1":[10,20,30,12,23,55],
                  "DEG2":[111,132,565,232,56,23]},
                 columns=["gruplar","DEG1","DEG2"])
df

gruplar  DEG1  DEG2
0       A    10   111
1       B    20   132
2       C    30   565
3       A    12   232
4       B    23    56
5       C    55    23

In [136]:
df["DEG1"]*9

0     90
1    180
2    270
3    108
4    207
5    495
Name: DEG1, dtype: int64

In [141]:
df_a = df.iloc[:,1:3]

In [145]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

DEG1      DEG2
0 -0.913548 -0.379627
1 -0.304516 -0.274035
2  0.304516  1.903161
3 -0.791741  0.228782
4 -0.121806 -0.656176
5  1.827096 -0.822105

In [ ]:
# apply 

In [151]:
import pandas as pd
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                  "DEG1":[10,20,30,12,23,55],
                  "DEG2":[111,132,565,232,56,23]},
                 columns=["gruplar","DEG1","DEG2"])
df

gruplar  DEG1  DEG2
0       A    10   111
1       B    20   132
2       C    30   565
3       A    12   232
4       B    23    56
5       C    55    23

In [149]:
df.apply(np.sum)

DEG1     150
DEG2    1119
dtype: int64

In [150]:
df.apply(np.mean)

DEG1     25.0
DEG2    186.5
dtype: float64

In [152]:
df.groupby("gruplar").apply(np.sum)

gruplar  DEG1  DEG2
gruplar                    
A            AA    22   343
B            BB    43   188
C            CC    85   588

# PİVOT TABLOLAR

In [153]:
import numpy as np
import pandas as pd
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [155]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [160]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [161]:
# pivot ile table

In [162]:
titanic.pivot_table("survived",index="sex",columns="class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [163]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [166]:
age = pd.cut(titanic["age"],[0,18,90])
age.head()

0    (18, 90]
1    (18, 90]
2    (18, 90]
3    (18, 90]
4    (18, 90]
Name: age, dtype: category
Categories (2, interval[int64]): [(0, 18] < (18, 90]]

In [167]:
titanic.pivot_table("survived",["sex",age],"class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

In [1]:
# DIŞ KAYNAKLARDAN VERİ OKUMA

In [2]:
import pandas as pd

In [12]:
?pd.read_csv

Signature:
pd.read_csv(
    ['filepath_or_buffer', "sep=','", 'delimiter=None', "header='infer'", 'names=None', 'index_col=None', 'usecols=None', 'squeeze=False', 'prefix=None', 'mangle_dupe_cols=True', 'dtype=None', 'engine=None', 'converters=None', 'true_values=None', 'false_values=None', 'skipinitialspace=False', 'skiprows=None', 'nrows=None', 'na_values=None', 'keep_default_na=True', 'na_filter=True', 'verbose=False', 'skip_blank_lines=True', 'parse_dates=False', 'infer_datetime_format=False', 'keep_date_col=False', 'date_parser=None', 'dayfirst=False', 'iterator=False', 'chunksize=None', "compression='infer'", 'thousands=None', "decimal=b'.'", 'lineterminator=None', 'quotechar=\'"\'', 'quoting=0', 'escapechar=None', 'comment=None', 'encoding=None', 'dialect=None', 'tupleize_cols=None', 'error_bad_lines=True', 'warn_bad_lines=True', 'skipfooter=0', 'doublequote=True', 'delim_whitespace=False', 'low_memory=True', 'memory_map=False', 'float_precision=None'],
)
Docstring:
Read CSV (co

In [8]:
# csv okuma
pd.read_csv("reading_data/ornekcsv.csv",sep=";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [11]:
# txt okuma
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [14]:
df = pd.read_excel("reading_data/ornekx.xlsx")

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [18]:
df.columns=("A","B","C")
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [20]:
# sıfırdan txt okuma
tips = pd.read_csv("reading_data/data.txt")
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4